title: Niharika Ravela
logo: /assets/avatar-logo.png
description: Aspiring Data Scientist | [UNT Great Grad Fall 2023](https://www.unt.edu/commencement/great-grads/fall-2023#ravela)   
show_downloads: false
theme: jekyll-theme-minimal
