title: Niharika Ravela
logo: /assets/avatar.jpeg
description: >
  <br>
  Junior Data Scientist with a year of experience. UNT Great Grad Fall23.
  <br>
  <a href="https://www.linkedin.com/in/niharikaravela/" target="_blank">LinkedIn Profile</a> 
  <br>
  <a href="https://medium.com/@ravelaniharika93" target="_blank">Blog</a> 
  <br>
  <a href="https://github.com/Niharika-Ravela" target="_blank">Github</a> 
  <br>
  <a href="https://docs.google.com/document/d/1mxXTd6X4cVaQLyJnPPsZFNAWFuR2J4m9/edit?usp=drive_link&ouid=102825429026543386205&rtpof=true&sd=true" target="_blank">Resume</a> 
  <br>
theme: jekyll-theme-minimal
google_analytics: G-6KT8W6KFVP
