title: Niharika Ravela
logo: /assets/avatar.jpeg
description: >
  <br>
  Junior Data Scientist with a year of experience. UNT Great Grad Fall23.
  <br>
  <a href="https://www.linkedin.com/in/niharikaravela/" target="_blank">LinkedIn Profile</a> 
  <br>
  <a href="https://medium.com/@ravelaniharika93" target="_blank">Blog</a> 
  <br>
  <a href="https://github.com/Niharika-Ravela" target="_blank">Github</a> 
  <br>
  <a href="https://drive.google.com/file/d/1dXmPSgeV4p51GjlGwhp74KZqbQXndNso/view?usp=drive_link" target="_blank">Resume</a> 
  <br>
theme: jekyll-theme-minimal
google_analytics: G-6KT8W6KFVP
